/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[claim_id]
      ,[claim_no]
      ,[act_id]
      ,[act_no]
      ,[oa_dataaktaraschet]
      ,[oa_dataakta]
      ,[T1_dataVidmovy]
      ,[T1_dataZayavy]
      ,[T1_dataPovidStrah]
      ,[T1_dataPovidPoterp]
      ,[T1_dataVypadka]
      ,[T1_countDays]
      ,[oa_dataVymogy]
      ,[T1_dataZayavyPoterp]
      ,[T1_firstZayava]
      ,[T1_Perelik]
      ,[T1_SumZbytka]
      ,[T1_SumZbytkaFull]
      ,[Sum_Zbytka_akt]
      ,[reserv_limit]
      ,[T1_SumVregul]
      ,[T1_SumReservAll]
      ,[ReservDate]
      ,[BeginingDate]
      ,[T1_ProcVregul]
      ,[n_ord_ic]
  FROM [Dmart].[dbo].[rznu]