/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[gid]
      ,[CaseGID]
      ,[Number]
      ,[Date]
      ,[PostAddressGID]
      ,[Address]
      ,[MobileCommissarGID]
      ,[ActualDate]
      ,[IsFinished]
      ,[Notes]
      ,[BackToDirectionDate]
      ,[AttachedToCaseDate]
      ,[SentToAccountsCenterDate]
      ,[AuthorGID]
      ,[TypeGID]
      ,[StatusGID]
      ,[ActualPostAddressGID]
      ,[ActualAddress]
      ,[ObjectName]
      ,[ObjectGID]
      ,[SecurityTypeGID] - осмотр, и тд.. розмір збитку 
      ,[ServiceStationGID]
      ,[BranchGID]
      ,[Deleted]
      ,[ExpertAppraiserGID]
      ,[CreateDate]
  FROM [Oberon].[dbo].[CommissarExaminations]